### ISSUE TITLE
Serialize and Deserialize code(C++)

### ISSUE THREAD

**Issue by amitShindeGit** [ishangoyal13/Hacktoberfest2021#234]
Serialize and Deserialize code is not there in the C++ folder.

**Comment by amitShindeGit** [comment]
I made a PR on the same.

**Comment by ishangoyal13** [comment]
> I made a PR on the same.

kindly mention this issue in your PR

**Comment by amitShindeGit** [comment]
> > I made a PR on the same.
> 
> kindly mention this issue in your PR

Done.

**Comment by amitShindeGit** [comment]
Your repository is showing invalid at my Hacktoberfest page.
