### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Arjun31415** [ishangoyal13/Hacktoberfest2021#275]
Add Dijkstra's Shortest path algorithm in DAG

**Comment by rishabh-arya** [comment]
Hi there.....
I am Rishabh Arya and  a participant in hacktoberfest21. I am good in competitive programming and DSA. Kindly, assign me this issue so that I can fix it. 
Thank you....!!!

**Comment by Arjun31415** [comment]
> Hi there..... I am Rishabh Arya and a participant in hacktoberfest21. I am good in competitive programming and DSA. Kindly, assign me this issue so that I can fix it. Thank you....!!!

Sorry but I have already completed this

**Comment by rishabh-arya** [comment]
Okay @Arjun31415  no issues
