### ISSUE TITLE
Adding Maximum area of histogram problem in C++ folder

### ISSUE THREAD

**Issue by Chirag-creator17** [ishangoyal13/Hacktoberfest2021#516]
### Description

Adding maximum Area of histogram code in c++ folder

### Language

C++

### Domain

Stacks

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by iamsunil25** [comment]
@Chirag-creator17  i am working on this issue

**Comment by Chirag-creator17** [comment]
ok sorry , i didn't saw that i will close this issue
